### PR TITLE
Fixed config validation file

### PR DESCRIPTION
**Pull request by Sinacam**
These datasets don't have pre-split validation data.

### CODE REVIEW

**Comment by JamesLYC88** [comment]
For XXX_tune.yml, I think `val_file` should be specified as `null`.
Please try to run
```
python search_params.py --config example_config/XXX/XXX_tune.yml
```
to ensure all the parameter search configs are runnable.
(As in our regression test, functionalities of the parameter search are not checked.)

**Comment by JamesLYC88** [comment]
The parameter search cannot work even if `val_file` is specified as `null`.
The commit below in https://github.com/ASUS-AICS/LibMultiLabel/pull/197/ seems to break the parameter search for glove-related data sets.
image

**Comment by JamesLYC88** [comment]
The error message in https://github.com/ASUS-AICS/LibMultiLabel/blob/master/libmultilabel/nn/data_utils.py#L333 needs a fix.
Please revise `vector` to `embed_file` because `vector` has no value.
Thanks.

**Comment by Sinacam** [comment]
> The parameter search cannot work even if `val_file` is specified as `null`. The commit below in #197 seems to break the parameter search for glove-related data sets. image

I have looked into this error, and it needs more discussion. It is a very bad hack.
Since it affects only search_params.py and isn't what this PR is fixing, it should not be a blocker for this PR.

**Review by Eleven1Liu — APPROVED** [review]
LGTM!

**Comment by Eleven1Liu** [comment]
> The parameter search cannot work even if `val_file` is specified as `null`. The commit below in #197 seems to break the parameter search for glove-related data sets. image

@Sinacam @JamesLYC88 Issues for `search_params.py`. This should be fixed in #201  ?

**Comment by Eleven1Liu** [comment]
> For XXX_tune.yml, I think `val_file` should be specified as `null`. Please try to run
> 
> ```
> python search_params.py --config example_config/XXX/XXX_tune.yml
> ```
> 
> to ensure all the parameter search configs are runnable. (In our regression test, functionalities of the parameter search are not checked.)

@Sinacam @JamesLYC88 Are issues for `search_params.py` fixed in #201 ?

```yaml
# *_tune.yml
val_file: null
```
For example, 
https://github.com/ASUS-AICS/LibMultiLabel/blob/c213ad81224eecbcdca9464a5848dbb1a125f26e/example_config/EUR-Lex/bigru_lwan_tune.yml#L3

**Pull request merged**
